apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  namespace: blog
  generateName: new-pipeline-run-
spec:
  taskRunTemplate:
    serviceAccountName: pipeline
    podTemplate:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000 # this is the non root user for podman build task
        runAsGroup: 1000
        fsGroup: 1000
  pipelineRef:
    name: new-pipeline
  workspaces:
    - name: git-source 
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce 
          resources:
            requests:
              storage: 1Gi
    - name: registry-credentials
      secret:
        secretName: quayio-robot-credentials
    - name: git-credentials
      secret:
        secretName: git-credentials  
