apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  namespace: blog
  generateName: new-pipeline-run-
spec:
  taskRunTemplate:
    serviceAccountName: pipeline
  # openshift pipelines: oc adm policy add-scc-to-user privileged -z pipeline
  # oc adm policy add-cluster-role-to-user cluster-admin -z pipeline
  pipelineRef:
    name: pipeline-blog
  workspaces:
    - name: git-source 
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce 
          resources:
            requests:
              storage: 1Gi
    - name: registry-credentials
      secret:
        secretName: quayio-robot-credentials
    - name: git-credentials
      secret:
        secretName: git-credentials  
