apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: new-pipeline-run-
spec:
  serviceAccountName: pipeline # openshift pipelines: oc adm policy add-scc-to-user privileged -z pipeline
  pipelineRef:
    name: new-pipeline
  workspaces:
    - name: git-source 
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce 
          resources:
            requests:
              storage: 1Gi
    - name: registry-credentials
      secret:
        secretName: quayio-robot-credentials
    - name: git-credentials
      secret:
        secretName: git-credentials        