apiVersion: v1
kind: Secret
metadata:
  name: quayio-robot-credentials
  namespace: blog
data:
  config.json: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJiV0YxY21samFXOXpZVzUwYVdGbmIyUmxZMkZ6ZEhKdksyTnBjbTlpYjNRNlJsWldXa3d4TUV4QlJWYzNRakZZU1VnMVN6UlVWREl6V0VaRlNFRTRNRFJXVEVOYU1sZFBOMU5WTlZneFVFWkhSMUZJTmxsVlRrczRWVFpQTWsxTE1BPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==