apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: dev

namespace: blogmd-dev

bases:
  - ../../base

resources:
  - namespace.yaml

images:
- name: quay.io/telefonicadevops/blogrunner:latest
#  newName: image-registry.openshift-image-registry.svc:5000/blogmd/blogrunner
#  newTag: v1.0
