title: Blog Series
description: A compiled series of my day by day life stories and thoughts 
remote_theme: pages-themes/tactile@v0.2.0

plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-regex-replace
  - jekyll-highlight-param

show_dir_listing: false

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: "Containerfile.md"
    values:
      layout: filesyntax 
      title: Blog Series
      description: Syntax Highlighted File Contents
      lang: dockerfile  
  - scope:
      path: "cicd/argo/deployment.yaml.md"
    values:
      layout: filesyntax  
      title: Blog Series
      description: Syntax Highlighted File Contents     
      lang: yaml      
  - scope:
      path: "cicd/tekton/syntaxhl.md"
    values:
      layout: dirlisting  
      title: Blog Series
      description: Syntax Highlighted Directory List
      pretty_print_files: true          
  - scope:
      path: "cicd/tekton/README.md"
    values:
      layout: dirlisting        
      title: Blog Series
      description: Directory List
  - scope:
      path: "README.md"
    values:
      git: https://github.com/mauricioscastro/blog        
  - scope:
      path: ""
    values:
      layout: default  

    