title: Blog Series
description: A compiled series of real (or almost real) stories from my day by life and thoughts 
remote_theme: pages-themes/tactile@v0.2.0

plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-regex-replace
  - jekyll-highlight-param

show_dir_listing: false

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock