title: &main_title Blog Series
description: A compiled series of my day by day life stories and thoughts 
remote_theme: pages-themes/tactile@v0.2.0

plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-regex-replace
  - jekyll-highlight-param

show_dir_listing: false

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: "Containerfile.md"
    values:
      layout: &file_layout filesyntax 
      title: *main_title
      description: &file_desc Syntax Highlighted File Contents
  - scope:
      path: "cicd/argo/deployment.yaml.md"
    values:
      layout: *file_layout  
      title: *main_title
      description: *file_desc   
  - scope:
      path: "cicd/tekton/syntaxhl.md"
    values:
      layout: &dir_layout dirlisting  
      title: *main_title
      description: Syntax Highlighted Directory List
      pretty_print_files: true          
  - scope:
      path: "cicd/tekton/README.md"
    values:
      layout: *dir_layout        
      title: *main_title
      description: Directory List
  - scope:
      path: "README.md"
    values:
      git: https://github.com/mauricioscastro/blog     
  - scope:
      path: ""
    values:
      layout: default  
  #
  # remove front matter from markdown
  #
  - scope:
      path: "redhat/idp/cert+ldap/README.md"
    values:
      title: Tech Blog Series
      description: A compiled series of real world scenario stories from the business as usual days of a IT architect  
    