title: Tech Blog Series
description: A compiled series of real world scenario stories from the business as usual days of a IT architect
remote_theme: pages-themes/tactile@v0.2.0
destination: /tmp/tech_blog_series_site

plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-regex-replace

show_dir_listing: false

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock