trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: ls -la /
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# - task: KubernetesManifest@1
#   inputs:
#     action: 'deploy'
#     connectionType: 'kubernetesServiceConnection'
#     kubernetesServiceConnection: 'openshift-ccr-devops'
#     manifests: ''
