trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    find /home
  displayName: 'Run a multi-line script'

# - task: KubernetesManifest@1
#   inputs:
#     action: 'deploy'
#     connectionType: 'kubernetesServiceConnection'
#     kubernetesServiceConnection: 'openshift-ccr-devops'
#     manifests: ''
