---
apiVersion: v1
kind: Service
metadata:
  name: blogmd
  namespace: blogmd
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: blogmd

