apiVersion: v1
kind: Namespace
metadata:
  name: blog
  labels:
    name: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      volumes:
        - name: workdir
          emptyDir: {}
      containers:
        - name: blogrunner
          image: quay.io/mauriciosantiagodecastro/blogrunner
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: workdir
              mountPath: /workdir
          env:
            - name: GIT_REPO
              value: https://github.com/mauricioscastro/blog     
        - name: md2pdf
          image: bladerunner2020/markdown-to-file
          imagePullPolicy: Always
          volumeMounts:
            - name: workdir
              mountPath: &pdf_col_base_path /usr/local/documents/mscastro
          env:
            - name: PDF_COLLECTION_BASE_PATH
              value: *pdf_col_base_path           
          command: 
            - /bin/sh
          args: 
            - -c
            - |-
              while true; do 
                find $PDF_COLLECTION_BASE_PATH
                for md in `find $PDF_COLLECTION_BASE_PATH -name "*.md" -newermt "10 seconds ago" | grep -v 404`; do 
                  m2f $md pdf \
                    footerTemplate="<div style=\"font-size: 9px; margin: 0 auto;\"> <span class="pageNumber"></span> / <span class="totalPages"></span></div>" \
                    headerTemplate="<span/>" margin.top="0.8cm" 
                done
                sleep 10
              done             
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog
spec:
  ports:
    - port: 4000
  selector:
    app: blog
